### ISSUE TITLE
App not working on Android 11

### ISSUE THREAD

**Issue by Mession77** [lposidon/posidonLauncher#102]
I cannot select any apps in the drawer. Apps are listed but clicking on an app does not work.
I also cannot copy any app to the dock. In short: the app is not working at all since the last update.
Running version 1.19 / Android 11 / Google Pixel 4a 5G.

**Comment by jkc88** [comment]
Not only Android 11. Updating Posidon to 1.19 caused it to stop working on all my devices, running Android 10. The app drawer is unresponsive unless i turn off app labels. Then it works again. I reverted to 1.18 in the meantime.

**Comment by swodig112** [comment]
Hello
I'm having problems with posidon 1.19 on lineageos 17.1 (android 10) rooted with magisk
I can't click on anything in the app drawer (the search textbox works). I can launch apps by searching. Turning marquee option on and off didn't help. The back button gesture doesn't work neither.
I can press and long press apps in the drawer if I turn labels off.

**Comment by andrewshadura** [comment]
> Not only Android 11. Updating Posidon to 1.19 caused it to stop working on all my devices, running Android 10. The app drawer is unresponsive unless i turn off app labels. Then it works again. I reverted to 1.18 in the meantime.

Switching off marquee also helps.
