### ISSUE TITLE
Frequent crashes with notification badges enabled

### ISSUE THREAD

**Issue by ClockGen** [lposidon/posidonLauncher#18]
I can't determine exact reproduction steps, but after enabling notification badges in settings I get many crashes on long-tapping or simply opening apps in main menu.  
Attached file contains a bug report that's generated on each such crash.
[report.txt](https://github.com/leoxshn/posidonLauncher/files/4678566/report.txt)

**Comment by leoxshn** [comment]
does it still happen in 1.14?

**Comment by micwoj92** [comment]
For me yes. Everytime that a notification spawns examples: newpipe playback, sms, page in firefox plays a vid/sound  F-Droid update
the report seems to be same besides the device info.
It doesnt happen when app has persistent notification or with system apps
examples: email app sync and new email notif appears, default music player spawns notification about playing song. 

I can provide that crash log too if needed
