### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ClockGen** [lposidon/posidonLauncher#2]
Hello and thank you for such an interesting launcher. I have some feature requests:  

* Allow to disable notification feed on main screen. Currently two other options (a widget and rss feed) can be disabled, but not notification feed.  

* Add option to enable blur on dock. Blur in drawer is really nice, but the look feels "inconsistent" if the dock is not blurred too.  

* Add an option to select custom font. It's really awesome that there's an option to change fonts, but it'd even better to be able to load custom .ttfs.  

* Add an option to change font scale. Some inbuilt fonts have different scale and they look weird (titles in the drawer looks very small with posidon sans font, for example).  

* Increase maximum amount of possible rows in dock. Current amount (3 rows) seems a bit limiting, considering there's no "classic" home screen where you can drop icons.

* Support reordering of apps in a folder. Currently it's not possible to reorder icons inside a folder and to drop icons from folder back to dock, long-pressing them just calls their context menu.  

* Add support for oreo shortcuts. Since oreo, many apps can create "shortcuts", for example shortcuts to specific files in a file manager, etc. Since there are no other areas where shortcuts could go, maybe they can be created in dock?

* Add notification dots. Many launchers display a notification dot near an app icon if there's a notification that belongs to this app.

* Allow to set custom icons to folders too. Currently it's only possible to set custom icons for apps, but not folders.

**Comment by Purgeme** [comment]
I have one as well

An option to search all apps even the hidden ones, so we can hide apps not used frequently but still access them easily. Reduces cluster in app drawer
