### ISSUE TITLE
Hide background services from notification area

### ISSUE THREAD

**Issue by Donnnno** [lposidon/posidonLauncher#30]
Hi, first of all great launcher!
One of the first things I noticed is I wasn't able to hide some persistent notifications like telegram, signal background services, this is kinda annoying because it fills the whole screen.
Maybe it's something you can take a look at.
Thanks!

**Comment by leoxshn** [comment]
There's a "Hidden apps" button in notifications settings, there you can choose the apps who's notification you want to hide.
But you can't hide specific notifications yet
