### ISSUE TITLE
Rss feed can't add multiple entries from a single site 

### ISSUE THREAD

**Issue by aaronsasse95** [lposidon/posidonLauncher#32]
When trying to add multiple feeds from a single site it just replaces the original
https://www.cnbc.com/id/15837362/device/rss/rss.html
https://www.cnbc.com/id/15838368/device/rss/rss.html

**Comment by aaronsasse95** [comment]
@ellietheoracle

**Comment by kylejwatson** [comment]
I'm on version 1.14 and it seems I can only add one source no-matter the site, eg. Opensource.com and github.com, the latter always replaces the former. I'm going to build the latest later and see if I get the same, if so I'll try and work on a fix.

**Comment by kylejwatson** [comment]
Just saw this is potentially a duplicate or linked to #23 .

**Comment by theotheroracle** [comment]
i'm not sure, i was able to add multiple sources from different sites, just not from the *same* site, i had three added at the same time, so i'm pretty sure it's not the same issue .
