### ISSUE TITLE
Sort feed by age and not show every rss feed after another

### ISSUE THREAD

**Issue by dj-bauer** [lposidon/posidonLauncher#39]
I don't know if I am missing out on anything, but I get my RSS feed after another and not all sorted by age.
So it kinda looks like that
```
src1 new
src1 old
src1 oldest
src2 new
src2 old
src2 oldest
src3 new
src3 old
src3 oldest

```
But I'd like to have
```
src1 new
src2 new
src3 new
src1 old
src2 old
src3 old
src1 oldest
src2 oldest
src3 oldest
```
Is that possible to activate by an option?

**Comment by leoxshn** [comment]
posidon launcher might not be able to read time very well in some feeds. Can you please send your rss links?
Also not all rss feeds include time of publishing, so it might be that.

**Comment by dj-bauer** [comment]
I took this three:
https://www.hagen-bauer.de/atom.xml
http://lukesmith.xyz/rss.xml
https://www.dj-bauer.de/feeds/all.atom.xml
When I open them in my newsfeed program, I can see a publishment date.
