### ISSUE TITLE
[Question about fdroid] hello i love this launcher i just have a question about release

### ISSUE THREAD

**Issue by aelisya** [lposidon/posidonLauncher#44]
Hello,

I just want to know if the delay (one version), between F-droid version and store version is something on your side (want to remove bug, or promote it on the store first), or if its F-droid who is slow to update it.

(Just for information i use the store one, the question is only for know your rules on release, so like that if i have to install it to my friend i know witch one i have to install to them).

Thanks

**Comment by leoxshn** [comment]
Normally there's a small delay (1 or 2 days i think) between the Github release and an F-Droid update.
Every-time an app repository makes a release, F-Droid compiles the new version from source, to make sure the app is safe.

**Comment by aelisya** [comment]
ok so it on their end if the app is not on the same version thanks for the answer :)
