### ISSUE TITLE
Crash when long-pressing apps inside of folders in the dock

### ISSUE THREAD

**Issue by CallToPower** [lposidon/posidonLauncher#54]
The launcher crashes on long-pressing an app inside of a folder in the dock (e.g. to move it or access its properties).

Stack trace:

`java.lang.ClassCastException: posidon.launcher.items.App cannot be cast to posidon.launcher.items.Folder

Device.api: 29
Version.code: 65
Version.name: 1.17

at: posidon.launcher.items.users.ItemLongPress$insideFolder$1.onLongClick(ItemLongPress.kt:206)
at: android.view.View.performLongClickInternal(View.java:7339)
at: android.view.View.performLongClick(View.java:7297)
at: android.view.View.performLongClick(View.java:7315)
at: android.view.View$CheckForLongPress.run(View.java:27850)
at: android.os.Handler.handleCallback(Handler.java:883)
at: android.os.Handler.dispatchMessage(Handler.java:100)
at: android.os.Looper.loop(Looper.java:214)
at: android.app.ActivityThread.main(ActivityThread.java:7356)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by omm** [comment]
The same behavior:
java.lang.NullPointerException: null cannot be cast to non-null type posidon.launcher.items.Folder

Device.api: 28
Device.brand: Sony
Device.model: G8441
Version.code: 65
Version.name: 1.17

at: posidon.launcher.items.users.ItemLongPress$insideFolder$1.onLongClick(ItemLongPress.kt:206)
at: android.view.View.performLongClickInternal(View.java:6692)
at: android.view.View.performLongClick(View.java:6650)
at: android.view.View.performLongClick(View.java:6668)
at: android.view.View$CheckForLongPress.run(View.java:25869)
at: android.os.Handler.handleCallback(Handler.java:873)
at: android.os.Handler.dispatchMessage(Handler.java:99)
at: android.os.Looper.loop(Looper.java:280)
at: android.app.ActivityThread.main(ActivityThread.java:6706)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by brboi** [comment]
Same for me (I love your launcher, BTW 😃)

```
java.lang.NullPointerException: null cannot be cast to non-null type posidon.launcher.items.Folder

Device.api: 29
Device.brand: OnePlus
Device.model: ONEPLUS A3003
Version.code: 65
Version.name: 1.17

at: posidon.launcher.items.users.ItemLongPress$insideFolder$1.onLongClick(ItemLongPress.kt:206)
at: android.view.View.performLongClickInternal(View.java:7340)
at: android.view.View.performLongClick(View.java:7298)
at: android.view.View.performLongClick(View.java:7316)
at: android.view.View$CheckForLongPress.run(View.java:27873)
at: android.os.Handler.handleCallback(Handler.java:883)
at: android.os.Handler.dispatchMessage(Handler.java:100)
at: android.os.Looper.loop(Looper.java:214)
at: android.app.ActivityThread.main(ActivityThread.java:7356)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```

**Comment by brboi** [comment]
If someone has a clue on what's happening there, I could propose a PR to fix this.

**Comment by Dremor** [comment]
Same for me.
```java.lang.NullPointerException: null cannot be cast to non-null type posidon.launcher.items.Folder

Device.api: 29
Device.brand: Nokia
Device.model: Nokia 8.1
Version.code: 65
Version.name: 1.17

at: posidon.launcher.items.users.ItemLongPress$insideFolder$1.onLongClick(ItemLongPress.kt:206)
at: android.view.View.performLongClickInternal(View.java:7205)
at: android.view.View.performLongClick(View.java:7163)
at: android.view.View.performLongClick(View.java:7181)
at: android.view.View$CheckForLongPress.run(View.java:27298)
at: android.os.Handler.handleCallback(Handler.java:883)
at: android.os.Handler.dispatchMessage(Handler.java:100)
at: android.os.Looper.loop(Looper.java:214)
at: android.app.ActivityThread.main(ActivityThread.java:7397)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
Being a dev myself (but not an Android one), looks like something do not check for nullity somewhere in the drag & drop code.

**Comment by RezurrectBodg** [comment]
I have something to add: when long-pressed extremely carefully and your finger doesn't move, launcher doesn't crash. I think it has to deal with drag&drop fucntions.
