### ISSUE TITLE
Error installing on Android 11

### ISSUE THREAD

**Issue by CallToPower** [lposidon/posidonLauncher#55]
After upgrading to Android 11, the launcher has been uninstalled on upgrade and cannot be unstalled:

"Error installing Posidon Launcher - Failed to install due to an unknown error".

**Comment by leoxshn** [comment]
where did you install it from? GPlay, F-Droid or xda labs

**Comment by CallToPower** [comment]
I tried to install it via F-Droid.
Just tried it via Aurora (Play) Store: Same result, error message is "A conflicting package exists".

**Comment by leoxshn** [comment]
It looks like you had posidon launcher already installed. When installing an update from a new source, this message always pops up. Try taking a backup, uninstalling the app, then installing again and recovering the backup.
(really sorry for such a late reply)

**Comment by CallToPower** [comment]
No problem, it's not your job replying to my small problems ;)
After a week of inactivity and a restart (all stores displayed it as "uninstalled") I was able to install it via F-Droid and it installed just fine.
There is another issue now (apps not displayed in drawer) but that's not the issue here. Closing this issue!
