### ISSUE TITLE
posidon launcher: crash stack trace

### ISSUE THREAD

**Issue by 7azhigin** [lposidon/posidonLauncher#57]
java.lang.RuntimeException: Unable to start activity ComponentInfo{posidon.launcher/posidon.launcher.Main}: kotlin.TypeCastException: null cannot be cast to non-null type android.graphics.drawable.LayerDrawable

Device.api: 28
Device.brand: HUAWEI
Device.model: ANE-LX1
Version.code: 64
Version.name: 1.16

at: android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
at: android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at: android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
at: android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at: android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at: android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at: android.os.Handler.dispatchMessage(Handler.java:112)
at: android.os.Looper.loop(Looper.java:216)
at: android.app.ActivityThread.main(ActivityThread.java:7625)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
at: posidon.launcher.Main$1.invoke(Main.kt:311)
at: posidon.launcher.Main$1.invoke(Main.kt:62)
at: posidon.launcher.Main$2.invoke(Main.kt:376)
at: posidon.launcher.Main$2.invoke(Main.kt:62)
at: posidon.launcher.Main.onCreate(Main.kt:759)
at: android.app.Activity.performCreate(Activity.java:7458)
at: android.app.Activity.performCreate(Activity.java:7448)
at: android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
at: android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
at: android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at: android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
at: android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at: android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at: android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at: android.os.Handler.dispatchMessage(Handler.java:112)
at: android.os.Looper.loop(Looper.java:216)
at: android.app.ActivityThread.main(ActivityThread.java:7625)
at: java.lang.reflect.Method.invoke(Native Method)
at: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by leoxshn** [comment]
Try upgrading to 1.17.
Also, if you have just a crash log, send it by email next time please.
