### ISSUE TITLE
Add Native Look at A Glance Page / window

### ISSUE THREAD

**Issue by Pranab009** [lposidon/posidonLauncher#61]
Please add Native "Look at a Glance Page" 
(right swipe / left swipe)

(Glance page) can be added 
Favorite apps.
Frequent apps.
Any widgets.
Clock, calendar, clock etc.

 "At A Glance"
(like Microsoft launcher).
it is very useful features think about it if possible then add this features.

**Comment by leoxshn** [comment]
I will add most of those as cards, but there will only be one page.
Also, you can have unlimited widgets in 1.18 alpha builds
