### ISSUE TITLE
multi-page optional mode. FR

### ISSUE THREAD

**Issue by DI555** [lposidon/posidonLauncher#73]
yes, i see that it started like one-page launcher...
but, please!!! let it be with optional mode multi-page!!!
i used to use multi-page mode on other launchers, but i'd like to skip to posidon! i have a lot of apps... realy huge amount of its...and multi-page mode is what gets me more oxygen to use the launcher!!!

**Comment by leoxshn** [comment]
I will not add multipage mode, because that would add too much complexity to gestures, but if you want, you can fork the launcher and make a version with pages.
And if you want multiple pages, why not just use Lawnchair launcher?

**Comment by DI555** [comment]
Lawnchair seems being abandoned((...
i like Posidon look and functionality, but i really using a lots of apps,- without multy-page mode it'll be kind of unusability(((...
