### ISSUE TITLE
[Feature Request] Search the web using duckduckgo

### ISSUE THREAD

**Issue by mahmoudajawad** [lposidon/posidonLauncher#95]
First, thanks for the great and amazing launcher you made.

### Current State

Searching functionality of Posidon Launcher is amazing. I use Arabic names in my contacts list which renders many many launcher builti-in search feature not able to find most if not all of my contacts, while Posidon had no issues at all searching across my apps and contacts. However, I can't use it to search the web, except if a card-material result is available via duckduckgo.

### The Proposal
When users enters search term in the search field, two scenarios can occur:
- No search results at all with the message: "No results for SEARCH_TERM", instead show a button beneath the message with the action to open the default web browser with duckduckgo search query.
- Irregardless of whether search term returns results or not, if the keyboard enter key is hit open the default web browser with duckduckgo search query.

### More Thoughts
I think not showing suggested results from duckduckgo in the search results as currently is done except for card-material results is great and should remain the same, however being able to access duckduckgo search functionality on the wider ranger is also crucial to everyday users.

**Comment by mahmoudajawad** [comment]
@leoxshn, shall I close the issue since you labeled it as `done in test builds`? Or, you prefer that I keep it open and help you test it?

**Comment by leoxshn** [comment]
I will close it after I release the update, but if you want, you can test it at our telegram channel (t.me/posidonnews), or group (t.me/posidonlauncher)

**Comment by mahmoudajawad** [comment]
I see. I was wondering where the test builds are to be found. I'm not on Telegram but, to my surprise, I can preview the messages from the web if I go to the URI you mentioned, and I can see Feb. 13th build which I'll give a shot later and report back here what I find specifically to search behaviour.
