### ISSUE TITLE
Support custom Nextcloud News feed

### ISSUE THREAD

**Issue by RoiArthurB** [lposidon/posidonLauncher#98]
Hi!

I love your launcher, but I need something to have it flawless : I would like to add my personal Nextcloud News feed in the Posidon's feed! 🤗🤗🤗

Here's the Nextcloud news documentation : https://github.com/nextcloud/news/tree/master/docs

**Comment by leoxshn** [comment]
Nextcloud is an news aggregator, like posidon launcher, you can export its sources as an OPML file and import it to posidon launcher, or add them individually in the news sources screen. I will not add support for rss readers, i'd rather just improve the one built into the launcher, so there's no need for other ones.
